function cab(doc,titulo){doc.setFillColor(7,59,134);doc.rect(0,0,210,34,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('KMO GESTÃO',16,16);doc.setFontSize(9);doc.text('CNPJ 34.655.687/0001-15',16,23);doc.setTextColor(23,32,51);doc.setFontSize(15);doc.text(titulo,105,49,{align:'center'});doc.setDrawColor(200,163,74);doc.setLineWidth(1);doc.line(16,55,194,55)}
function rod(doc){doc.setDrawColor(7,59,134);doc.line(16,278,194,278);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(90);doc.text('K M O Gestão LTDA – EPP • '+END,105,284,{align:'center'})}
function linha(doc,label,valor,y){doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text(label,18,y);doc.setFont('helvetica','normal');let x=18+doc.getTextWidth(label)+3;doc.text(String(valor||'—'),x,y)}
function texto(doc,txt,x,y,w){let a=doc.splitTextToSize(String(txt||''),w);doc.text(a,x,y);return y+a.length*5}
function dataLonga(s){let p=(s||'').split('/');if(p.length<3)return s||'';let m=['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'];return (+p[0])+' de '+m[(+p[1])-1]+' de '+p[2]}
function porExtenso(v){if(window.valorPorExtenso)return window.valorPorExtenso(v);return brl(v)}
function recibo(){let d=dados(),{jsPDF}=window.jspdf,doc=new jsPDF();cab(doc,'RECIBO DE NOTA FISCAL');linha(doc,'NÚMERO DO RECIBO:',d.nf+' / '+d.ano,67);linha(doc,'NOTA FISCAL Nº:',d.nf,76);linha(doc,'VALOR:',brl(d.valor),85);doc.setFont('helvetica','normal');doc.setFontSize(10);let y=102;doc.text('A empresa '+EMP+', inscrita no CNPJ nº '+CNPJ+', declara ter recebido de:',18,y);doc.setFont('helvetica','bold');y=texto(doc,d.tom.toUpperCase(),18,y+10,174)+5;doc.setFont('helvetica','normal');y=texto(doc,'a importância de '+porExtenso(d.valor)+', referente à Nota Fiscal nº '+d.nf+', correspondente aos serviços prestados.',18,y,174)+7;doc.setFillColor(242,244,247);doc.roundedRect(18,y,174,24,3,3,'F');doc.setFont('helvetica','bold');doc.text('DADOS BANCÁRIOS',23,y+7);doc.setFont('helvetica','normal');doc.text(d.banco+' • AGÊNCIA '+d.ag+' • CONTA '+d.conta,23,y+15);y+=38;let dt=$('blankRecibo').checked?'Tianguá, ____/____/'+d.ano:'Tianguá, '+dataLonga(d.data)+'.';doc.text(dt,105,y,{align:'center'});doc.line(55,y+28,155,y+28);doc.setFont('helvetica','bold');doc.text(d.rep,105,y+35,{align:'center'});rod(doc);doc.save('RECIBO_NF_'+d.nf+'.pdf')}
function requerimento(){let d=dados(),{jsPDF}=window.jspdf,doc=new jsPDF();cab(doc,'REQUERIMENTO DE PAGAMENTO');let y=70,dt=$('dateReq').checked?dataLonga(d.data):'____ de ______________ de '+d.ano;doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('TIANGUÁ, '+dt.toUpperCase(),18,y);doc.setFont('helvetica','normal');y=texto(doc,'A empresa '+EMP+', inscrita no CNPJ nº '+CNPJ+', estabelecida na '+END+', por meio de seu representante legal infra-assinado, vem respeitosamente requerer o pagamento a:',18,y+13,174)+6;doc.setFont('helvetica','bold');y=texto(doc,d.tom.toUpperCase(),18,y,174)+6;doc.setFont('helvetica','normal');y=texto(doc,'da importância de '+porExtenso(d.valor)+' ('+brl(d.valor)+'), referente à Nota Fiscal nº '+d.nf+', pelos serviços prestados.',18,y,174)+7;linha(doc,'BANCO:',d.banco,y);linha(doc,'AGÊNCIA:',d.ag,y+8);linha(doc,'CONTA:',d.conta,y+16);doc.text('Nestes termos, pede deferimento.',18,y+34);doc.text('Para maior clareza, firmamos o presente.',18,y+42);doc.line(55,y+76,155,y+76);doc.setFont('helvetica','bold');doc.text(d.rep,105,y+83,{align:'center'});rod(doc);doc.save('REQUERIMENTO_NF_'+d.nf+'.pdf')}
function gerar(t){t==='recibo'?recibo():requerimento()}function gerarAmbos(){recibo();setTimeout(requerimento,450)}
