BANKS['6-3']=[
{t:'Cartografia',q:'Um aluno observa um mapa-múndi e percebe que a Groenlândia parece quase do tamanho da África. Qual explicação é mais adequada?',o:['A Groenlândia realmente tem área semelhante à África','Toda projeção cartográfica pode gerar distorções ao representar a Terra esférica em uma superfície plana','Mapas não possuem escala','A África foi desenhada menor por estar no Hemisfério Sul'],a:1,h:'Transformar uma superfície curva em plana traz consequências.',e:'Projeções cartográficas sempre produzem algum tipo de distorção de área, forma, distância ou direção.'},
{t:'Coordenadas',q:'Qual ponto está simultaneamente no Hemisfério Sul e a oeste de Greenwich?',o:['20° N, 40° E','15° S, 30° W','10° N, 25° W','35° S, 15° E'],a:1,h:'Procure S para sul e W para oeste.',e:'15° S indica Hemisfério Sul e 30° W indica oeste de Greenwich.'},
{t:'Orientação',q:'Um explorador caminha para nordeste e depois decide seguir exatamente na direção oposta. Para onde deve ir?',o:['Sudeste','Noroeste','Sudoeste','Norte'],a:2,h:'A direção oposta troca norte por sul e leste por oeste.',e:'O oposto de nordeste é sudoeste.'},
{t:'Escala',q:'Em uma escala 1:1.000.000, 1 cm no mapa corresponde a quantos quilômetros na realidade?',o:['1 km','10 km','100 km','1.000 km'],a:1,h:'1.000.000 cm equivalem a 10 km.',e:'1.000.000 cm = 10.000 m = 10 km.'},
{t:'Relevo',q:'Rios podem modificar o relevo porque:',o:['A água corrente pode erodir, transportar e depositar sedimentos','Rios apenas ocupam formas prontas e nunca alteram o terreno','Água não transporta partículas','Todo rio cria montanhas'],a:0,h:'Pense na ação da água sobre rochas e sedimentos.',e:'A água fluvial participa da erosão, transporte e deposição de materiais.'},
{t:'Clima',q:'Duas cidades estão na mesma latitude, mas uma fica no litoral e outra no interior. A diferença climática pode estar relacionada principalmente à:',o:['Maritimidade e continentalidade','Linha do Equador','Rotação da Lua','Escala do mapa'],a:0,h:'O oceano reduz variações térmicas em muitas áreas costeiras.',e:'A proximidade ou distância do oceano influencia umidade e amplitude térmica.'},
{t:'Oceanos',q:'A evaporação oceânica contribui diretamente para qual etapa do ciclo da água?',o:['Formação de vapor de água na atmosfera','Formação de rochas magmáticas','Movimento das placas tectônicas','Criação de relevo glacial'],a:0,h:'A água líquida recebe energia e passa ao estado gasoso.',e:'A evaporação transforma água líquida em vapor, alimentando a umidade atmosférica.'},
{t:'Clima e vegetação',q:'Uma região com pouca chuva durante quase todo o ano tende a apresentar vegetação:',o:['Com adaptações para reduzir perda de água','Obrigatoriamente formada por árvores muito altas e densas','Sem nenhuma adaptação à seca','Igual à floresta equatorial'],a:0,h:'Pense em folhas pequenas, raízes profundas ou armazenamento de água.',e:'Ambientes secos selecionam plantas com adaptações à escassez hídrica.'},
{t:'População',q:'Uma área pode ter população absoluta alta e densidade baixa quando:',o:['Tem muitos habitantes distribuídos em uma área territorial muito extensa','Tem poucos habitantes em área pequena','Não possui habitantes','Sua área é sempre urbana'],a:0,h:'Densidade depende da relação entre habitantes e área.',e:'Um território muito grande pode diluir uma população numerosa e resultar em baixa densidade média.'},
{t:'Paisagem',q:'Uma paisagem urbana muda com a construção de uma avenida e a retirada de vegetação. Esse exemplo mostra que:',o:['As paisagens são fixas e não se transformam','A ação humana pode transformar elementos naturais e culturais da paisagem','Somente fenômenos naturais alteram paisagens','Cidade não é paisagem geográfica'],a:1,h:'Observe a presença de obras humanas sobre o espaço.',e:'Paisagens resultam da interação entre elementos naturais e ações sociais, mudando ao longo do tempo.'}
];
