BANKS['7-1']=[
{t:'Continentes',q:'Qual continente reúne a maior população mundial?',o:['Oceania','Ásia','Europa','Antártida'],a:1,h:'China e Índia estão nesse continente.',e:'A Ásia concentra a maior parcela da população mundial.'},
{t:'África',q:'A Linha do Equador atravessa a África. Isso significa que o continente possui terras:',o:['Apenas no Hemisfério Norte','Apenas no Hemisfério Sul','Nos hemisférios Norte e Sul','Somente no Hemisfério Oeste'],a:2,h:'A linha divide Norte e Sul.',e:'Como o Equador atravessa a África, o continente possui áreas ao norte e ao sul dessa linha.'},
{t:'Ásia',q:'Qual fator ajuda a explicar grandes concentrações populacionais em partes do sul e leste da Ásia?',o:['Presença de áreas férteis, água, cidades e atividades econômicas','Gelo permanente em todo o território','Ausência de rios','Falta total de cidades'],a:0,h:'Pense nas condições históricas e naturais favoráveis à ocupação.',e:'Água, planícies férteis, antigas áreas agrícolas e grandes centros urbanos ajudam a explicar altas densidades.'},
{t:'Europa',q:'O Meridiano de Greenwich, usado como referência de longitude, passa por qual continente?',o:['Europa','Oceania','Antártida apenas','América do Sul apenas'],a:0,h:'Ele passa pelo Reino Unido.',e:'Greenwich fica em Londres, no continente europeu.'},
{t:'Oceania',q:'A Oceania é formada por:',o:['Apenas a Austrália','Austrália, Nova Zelândia e numerosos arquipélagos e ilhas do Pacífico','Somente ilhas vulcânicas','Austrália e Antártida'],a:1,h:'O continente inclui várias ilhas do Pacífico.',e:'Oceania inclui a Austrália e numerosas ilhas e arquipélagos, incluindo a Nova Zelândia.'},
{t:'Antártida',q:'Por que a Antártida não possui população permanente numerosa como outros continentes?',o:['Condições climáticas extremas e forte isolamento','Falta de relevo','Porque não é um continente','Porque não existe água em forma de gelo'],a:0,h:'Pense nas condições ambientais para ocupação humana contínua.',e:'Frio extremo, isolamento e condições ambientais rigorosas limitam a ocupação permanente.'},
{t:'Oceanos',q:'O Oceano Atlântico separa principalmente quais conjuntos continentais?',o:['Américas de Europa e África','Ásia de Oceania','Europa de Ásia','Antártida de África apenas'],a:0,h:'Pense nas margens leste das Américas e oeste da Europa/África.',e:'O Atlântico está entre as Américas e Europa/África.'},
{t:'Climas',q:'Áreas próximas ao Equador tendem a receber maior quantidade de energia solar ao longo do ano. Isso favorece:',o:['Temperaturas geralmente elevadas','Gelo permanente em todas as áreas','Ausência de evaporação','Noites polares durante todo o ano'],a:0,h:'Os raios solares chegam mais diretamente em baixas latitudes.',e:'Baixas latitudes recebem energia solar mais diretamente e tendem a ser mais quentes.'},
{t:'Vegetação',q:'Savanas são formações vegetais geralmente marcadas por:',o:['Predomínio de gramíneas com árvores e arbustos espaçados','Florestas sempre densas e úmidas','Ausência completa de plantas','Vegetação exclusivamente de gelo'],a:0,h:'Pense em paisagens abertas de clima tropical com estação seca.',e:'Savanas combinam gramíneas e árvores/arbustos espaçados, com adaptações à sazonalidade das chuvas.'},
{t:'População',q:'Densidade demográfica é:',o:['Número total de habitantes de um país','Relação entre número de habitantes e área ocupada','Quantidade de cidades por continente','Taxa de chuva por habitante'],a:1,h:'É uma relação entre pessoas e espaço.',e:'Densidade demográfica expressa quantos habitantes existem, em média, por unidade de área.'}
];
