BANKS['6-1']=[
{t:'Continentes',q:'Em qual continente está localizado o Brasil?',o:['Ásia','América','Europa','África'],a:1,h:'Pense no continente que reúne América do Norte, Central e do Sul.',e:'O Brasil fica na América do Sul, uma das porções do continente americano.'},
{t:'Localização',q:'Qual linha imaginária atravessa a região central da África e divide a Terra em Hemisfério Norte e Hemisfério Sul?',o:['Meridiano de Greenwich','Trópico de Câncer','Linha do Equador','Círculo Polar Ártico'],a:2,h:'Ela corresponde à latitude 0°.',e:'A Linha do Equador é a referência de latitude 0° e separa os hemisférios Norte e Sul.'},
{t:'Orientação',q:'Qual ponto cardeal indica a direção em que o Sol nasce aproximadamente?',o:['Leste','Oeste','Norte','Sul'],a:0,h:'Também é chamado de Este em alguns mapas.',e:'O Sol nasce aproximadamente a leste e se põe aproximadamente a oeste.'},
{t:'Coordenadas',q:'O Meridiano de Greenwich é a principal referência para medir:',o:['Altitude','Latitude','Longitude','Profundidade'],a:2,h:'Essa medida indica posições a leste ou a oeste.',e:'Greenwich marca a longitude 0° e serve de referência para as longitudes.'},
{t:'Linhas imaginárias',q:'Qual linha imaginária fica aproximadamente a 23,5° de latitude sul?',o:['Trópico de Câncer','Linha do Equador','Trópico de Capricórnio','Círculo Polar Ártico'],a:2,h:'Ela está no Hemisfério Sul.',e:'O Trópico de Capricórnio está aproximadamente a 23,5° sul.'},
{t:'Relevo',q:'Montanhas, planaltos, planícies e depressões são exemplos de:',o:['Tipos de clima','Formas de relevo','Oceanos','Fusos horários'],a:1,h:'São diferentes formas da superfície terrestre.',e:'Esses termos classificam formas do relevo da superfície terrestre.'},
{t:'Oceanos',q:'Qual é o maior oceano do planeta?',o:['Atlântico','Índico','Pacífico','Glacial Ártico'],a:2,h:'Ele fica entre as Américas e a Ásia/Oceania.',e:'O Oceano Pacífico é o maior em extensão.'},
{t:'Climas',q:'O clima equatorial é geralmente caracterizado por:',o:['Frio intenso e pouca chuva','Calor e muita umidade','Verões secos e invernos rigorosos','Baixas temperaturas o ano inteiro'],a:1,h:'Pense nas áreas próximas à Linha do Equador.',e:'O clima equatorial costuma ter temperaturas elevadas e chuvas abundantes.'},
{t:'Vegetação',q:'Qual formação vegetal apresenta plantas baixas, musgos e líquens em regiões muito frias?',o:['Savana','Tundra','Floresta Tropical','Pradaria'],a:1,h:'Ela é comum em altas latitudes.',e:'A tundra possui vegetação baixa adaptada ao frio intenso.'},
{t:'População',q:'Qual situação tende a favorecer a concentração da população?',o:['Disponibilidade de água e oportunidades de trabalho','Ausência de água','Gelo permanente','Isolamento extremo'],a:0,h:'Pense no que facilita moradia e trabalho.',e:'Água, infraestrutura, serviços e atividades econômicas favorecem a concentração populacional.'}
];
