BANKS['6-2']=[
{t:'Continentes',q:'Uma viagem sai do Brasil e cruza o Oceano Atlântico em direção ao leste até chegar à costa ocidental africana. Em qual continente termina a viagem?',o:['África','Ásia','Europa','Oceania'],a:0,h:'Esse continente fica a leste do Atlântico Sul.',e:'A costa ocidental da África está do outro lado do Atlântico em relação ao Brasil.'},
{t:'Hemisférios',q:'Um ponto localizado a 15° N e 20° E está em quais hemisférios?',o:['Sul e Oeste','Norte e Leste','Norte e Oeste','Sul e Leste'],a:1,h:'N indica Norte; E indica leste.',e:'15° N indica Hemisfério Norte e 20° E indica Hemisfério Leste.'},
{t:'Orientação',q:'Se uma cidade está a sudeste de outra, em que direção devemos viajar para voltar à cidade de origem?',o:['Sudeste','Nordeste','Noroeste','Sudoeste'],a:2,h:'Procure a direção oposta ao sudeste.',e:'A direção oposta a sudeste é noroeste.'},
{t:'Escala',q:'Em um mapa, 1 cm representa 50 km. Duas cidades estão separadas por 4 cm. Qual distância aproximada entre elas?',o:['12,5 km','54 km','200 km','500 km'],a:2,h:'Multiplique a distância do mapa pelo valor representado por cada centímetro.',e:'4 × 50 km = 200 km.'},
{t:'Relevo',q:'Qual alternativa melhor diferencia planalto e planície?',o:['Planalto é sempre mais baixo que planície','No planalto predomina erosão; na planície, sedimentação','Planície só existe perto do mar','Planalto não sofre erosão'],a:1,h:'Pense nos processos que predominam na modelagem do relevo.',e:'Em termos geomorfológicos, nos planaltos predomina a erosão e nas planícies a sedimentação.'},
{t:'Atmosfera',q:'Tempo atmosférico e clima são conceitos diferentes porque:',o:['Tempo descreve condições de curto prazo; clima envolve padrões de longo período','Clima muda a cada hora e tempo dura décadas','São exatamente a mesma coisa','Tempo só existe no inverno'],a:0,h:'Compare a escala de tempo analisada.',e:'Tempo é o estado momentâneo da atmosfera; clima é o comportamento médio observado por longos períodos.'},
{t:'Oceanos',q:'Por que os oceanos são importantes para o clima?',o:['Porque impedem totalmente as chuvas','Porque armazenam e redistribuem calor e umidade','Porque não trocam energia com a atmosfera','Porque existem apenas em áreas frias'],a:1,h:'Pense na troca de calor e umidade entre água e atmosfera.',e:'Oceanos armazenam calor, fornecem umidade e influenciam temperaturas e precipitações.'},
{t:'Climas',q:'Uma área localizada em grande altitude tende a apresentar temperaturas mais baixas principalmente porque:',o:['A altitude influencia a temperatura do ar','Está sempre mais próxima do Equador','Possui mais oceanos','Recebe mais luz solar'],a:0,h:'Compare uma cidade em serra com outra no nível do mar.',e:'Com o aumento da altitude, a temperatura do ar tende a diminuir.'},
{t:'Vegetação',q:'A relação entre clima e vegetação pode ser observada porque:',o:['A vegetação não depende de água ou temperatura','Temperatura e disponibilidade de água influenciam quais plantas conseguem se desenvolver','Toda vegetação do mundo é igual','Somente o relevo determina as plantas'],a:1,h:'Pense nas necessidades de água e temperatura das plantas.',e:'Clima, solo e relevo interagem, e temperatura e água são fatores importantes para a vegetação.'},
{t:'População',q:'Duas regiões têm o mesmo tamanho. A região A tem 1 milhão de habitantes e a B tem 4 milhões. Qual possui maior densidade demográfica?',o:['A','B','As duas têm a mesma','Não é possível comparar'],a:1,h:'Densidade relaciona população e área.',e:'Como as áreas são iguais, a região com mais habitantes possui maior densidade.'}
];
