BANKS['7-3']=[
{t:'América',q:'Dois países têm população semelhante, mas um possui território quatro vezes maior. Mantidas essas condições, é provável que o país maior apresente:',o:['Maior densidade por definição','Menor densidade demográfica média','A mesma densidade obrigatoriamente','População absoluta quatro vezes maior'],a:1,h:'Densidade = população dividida pela área.',e:'Com população semelhante e área muito maior, a densidade média tende a ser menor.'},
{t:'África',q:'Uma análise que explica conflitos territoriais apenas pelo clima, ignorando história colonial, fronteiras e interesses econômicos, é limitada porque:',o:['Fenômenos geográficos resultam da interação de fatores naturais, históricos, sociais e econômicos','O clima nunca influencia sociedades','História não interfere no território','Fronteiras são fenômenos exclusivamente naturais'],a:0,h:'A Geografia busca relações entre múltiplos fatores.',e:'Questões territoriais complexas exigem considerar fatores históricos, políticos, econômicos, culturais e ambientais.'},
{t:'Ásia',q:'A instalação de indústrias próximas a portos e grandes mercados consumidores pode reduzir custos principalmente de:',o:['Circulação e logística','Latitude','Formação do relevo','Rotação da Terra'],a:0,h:'Pense no transporte de matérias-primas e produtos.',e:'Proximidade de portos, infraestrutura e mercados pode reduzir custos logísticos e facilitar fluxos comerciais.'},
{t:'Europa',q:'Em uma sociedade com baixa natalidade e alta expectativa de vida, qual tendência demográfica pode ocorrer?',o:['Envelhecimento da população','Crescimento automático da população infantil','Desaparecimento das cidades','Aumento obrigatório da natalidade'],a:0,h:'Compare o peso relativo de jovens e idosos.',e:'Baixa natalidade e maior longevidade elevam a participação relativa de idosos.'},
{t:'Oceania',q:'A forte concentração populacional em determinadas faixas costeiras da Austrália evidencia que:',o:['População se distribui de modo desigual conforme condições ambientais e socioeconômicas','Todo litoral mundial é igualmente povoado','Clima não interfere na ocupação','O interior não possui território'],a:0,h:'Relacione ambiente, infraestrutura e economia.',e:'A distribuição populacional é desigual e responde a fatores físicos, históricos e econômicos.'},
{t:'Antártida',q:'O uso da Antártida para pesquisa científica internacional reforça a importância de:',o:['Cooperação internacional e produção de conhecimento sobre o sistema terrestre','Urbanização intensiva do continente','Exploração urbana permanente','Transformação imediata em área agrícola'],a:0,h:'Pense no valor científico do gelo, clima e ecossistemas polares.',e:'A pesquisa antártica contribui para estudos climáticos, oceânicos e ambientais e envolve cooperação entre países.'},
{t:'Oceanos',q:'O aumento do nível médio do mar pode afetar especialmente:',o:['Áreas costeiras baixas e cidades litorâneas','Somente montanhas muito altas','Apenas regiões sem litoral','Unicamente desertos continentais'],a:0,h:'Pense nas áreas mais próximas da altitude do nível do mar.',e:'Áreas costeiras baixas são mais vulneráveis a inundações, erosão costeira e avanço do mar.'},
{t:'Climas',q:'Uma cidade substitui extensas áreas vegetadas por asfalto e concreto. Qual fenômeno urbano pode se intensificar?',o:['Ilha de calor urbana','Formação de geleiras','Redução obrigatória da temperatura','Movimento das placas tectônicas'],a:0,h:'Materiais urbanos absorvem e liberam calor de modo diferente da vegetação.',e:'Impermeabilização e baixa cobertura vegetal podem aumentar temperaturas e intensificar ilhas de calor.'},
{t:'Vegetação',q:'A fragmentação de uma floresta em pequenos blocos isolados pode prejudicar espécies porque:',o:['Reduz conexão entre habitats e dificulta deslocamento e reprodução','Aumenta sempre o habitat disponível','Elimina todos os efeitos de borda','Não altera ecossistemas'],a:0,h:'Pense na necessidade de circulação entre áreas de habitat.',e:'Fragmentação reduz conectividade, cria efeitos de borda e pode isolar populações biológicas.'},
{t:'População',q:'Uma cidade cresce rapidamente sem expansão equivalente de moradia, saneamento e transporte. Qual interpretação é mais adequada?',o:['Crescimento populacional e urbano pode gerar pressão sobre infraestrutura e ampliar desigualdades','Todo crescimento urbano melhora automaticamente todos os serviços','Infraestrutura não tem relação com urbanização','Saneamento é irrelevante para qualidade de vida'],a:0,h:'Compare ritmo de crescimento e capacidade dos serviços urbanos.',e:'Quando infraestrutura não acompanha o crescimento, podem aumentar déficits de moradia, mobilidade e saneamento.'}
];
