BANKS['7-2']=[
{t:'América',q:'A concentração de grandes cidades no litoral de vários países americanos pode ser relacionada, entre outros fatores, a:',o:['Processos históricos de ocupação, portos e redes de transporte','Ausência histórica de comércio marítimo','Clima polar em todo o litoral','Proibição de atividades econômicas costeiras'],a:0,h:'Pense no papel dos portos e da colonização.',e:'Ocupação histórica, portos, comércio e infraestrutura ajudaram a concentrar cidades em muitas áreas litorâneas.'},
{t:'África',q:'Em várias partes da África, fronteiras políticas atuais não coincidem com limites de grupos étnicos e culturais. Isso se relaciona historicamente:',o:['À divisão colonial do território por potências europeias','Ao movimento das placas tectônicas','À Linha do Equador','À formação dos oceanos'],a:0,h:'Pense no imperialismo europeu dos séculos XIX e XX.',e:'Muitas fronteiras foram traçadas durante a colonização europeia sem respeitar integralmente territórios culturais preexistentes.'},
{t:'Ásia',q:'O crescimento de megacidades asiáticas está associado principalmente a:',o:['Urbanização, industrialização e concentração de serviços e empregos','Desaparecimento das atividades econômicas','Diminuição total das migrações','Ausência de infraestrutura urbana'],a:0,h:'Pense no movimento de pessoas e atividades para grandes centros.',e:'Industrialização, serviços, migrações e urbanização impulsionam o crescimento de grandes metrópoles.'},
{t:'Europa',q:'A elevada urbanização de grande parte da Europa significa que:',o:['A maior parte da população vive em áreas urbanas','Não existem áreas rurais','Toda população trabalha na indústria','Não há agricultura no continente'],a:0,h:'Urbanização trata da proporção da população que vive em cidades.',e:'Alta urbanização significa predominância da população urbana, não ausência de áreas rurais.'},
{t:'Oceania',q:'Por que a população australiana se concentra principalmente em faixas litorâneas?',o:['Partes do interior são áridas, enquanto áreas costeiras reúnem melhores condições e grandes cidades','O interior é totalmente coberto por gelo','O litoral não possui cidades','A Austrália não possui desertos'],a:0,h:'Compare condições ambientais do interior e da costa.',e:'O interior australiano possui extensas áreas áridas, enquanto o litoral concentra infraestrutura, cidades e condições mais favoráveis.'},
{t:'Antártida',q:'A presença de estações científicas na Antártida mostra que o continente:',o:['Possui ocupação principalmente temporária voltada à pesquisa','Possui grandes metrópoles permanentes','É densamente povoado','Não recebe seres humanos'],a:0,h:'Pesquisadores permanecem por períodos determinados.',e:'A principal presença humana é temporária e ligada à pesquisa científica.'},
{t:'Oceanos',q:'Rotas marítimas internacionais são importantes porque:',o:['Conectam áreas produtoras e consumidoras e transportam grandes volumes de mercadorias','Substituem completamente todos os transportes terrestres','Não participam do comércio mundial','Existem apenas para turismo'],a:0,h:'Pense no comércio de mercadorias entre continentes.',e:'O transporte marítimo movimenta grandes volumes e integra redes de comércio global.'},
{t:'Climas',q:'Uma corrente marítima quente pode influenciar áreas costeiras ao:',o:['Transportar calor e modificar condições de temperatura e umidade','Eliminar toda umidade do ar','Impedir qualquer vento','Alterar a latitude do continente'],a:0,h:'Correntes oceânicas redistribuem energia.',e:'Correntes marítimas redistribuem calor e podem afetar temperaturas e umidade do litoral.'},
{t:'Vegetação',q:'O desmatamento de uma floresta pode provocar, entre outras consequências:',o:['Perda de biodiversidade e alterações no ciclo da água','Aumento automático de todas as espécies','Fim da erosão','Formação imediata de geleiras'],a:0,h:'Pense nas funções ecológicas da cobertura vegetal.',e:'A retirada da cobertura vegetal pode reduzir biodiversidade, alterar fluxos de água e aumentar erosão.'},
{t:'População',q:'Uma região apresenta muitas oportunidades de emprego e boa infraestrutura. Qual processo demográfico pode ser estimulado?',o:['Atração de migrantes','Desaparecimento obrigatório da população','Redução automática da urbanização','Fim da mobilidade populacional'],a:0,h:'Pessoas podem se deslocar em busca de melhores condições.',e:'Empregos e infraestrutura podem atuar como fatores de atração migratória.'}
];
