const introLines=['Vamos abrir o mapa e começar a missão!','Bússola conferida. Observe a pergunta com atenção!','Nova parada! Use o raciocínio geográfico.','Chegamos a mais uma fase. Compare as pistas antes de responder.','A aventura continua! Localização e paisagem contam uma história.','Está frio por aqui! Mesmo assim, mantenha a curiosidade aquecida.','Hora de navegar por uma nova ideia!','Clima no radar. Pense nas relações entre os elementos.','Observe como ambiente e vida se conectam.','Desafio final! Use tudo o que você aprendeu.'];
let grade=null,level=null,index=0,hits=0,answered=false,voiceOn=true,fxOn=true,audioCtx=null,answersLog=[],currentQuestions=[];
const $=s=>document.querySelector(s), mascotStage=$('#mascotStage'), speechBox=$('#speechBox'), speechText=$('#speechText');

const SCENES=[
{src:'scenes/amazonia.jpg',title:'🌿 Floresta Amazônica e Rios',text:'Hidrografia, biodiversidade, paisagem e relações sociedade-natureza.'},
{src:'scenes/pantanal.jpg',title:'🐊 Pantanal Alagado e Planícies',text:'Planícies, ciclos de cheia, fauna e dinâmica das águas.'},
{src:'scenes/serra_gaucha.jpg',title:'🌲 Serra Gaúcha e Araucárias',text:'Relevo, clima subtropical, paisagens rurais e Mata de Araucárias.'},
{src:'scenes/chapada.jpg',title:'⛰️ Cachoeiras e Chapada Diamantina',text:'Relevo, erosão, rios, cachoeiras e paisagens de altitude.'},
{src:'scenes/lencois.jpg',title:'🏜️ Lençóis e Delta do Piauí',text:'Dunas, litoral, água e transformação das paisagens.'},
{src:'scenes/ceara.jpg',title:'🌊 Ceará: Praias e Serra',text:'Litoral, serras, clima, biodiversidade e ocupação humana.'},
{src:'scenes/litoral_agreste.jpg',title:'🐚 Litoral Sul e Agreste',text:'Ambientes costeiros, agricultura, paisagens culturais e transições naturais.'},
{src:'scenes/caatinga.jpg',title:'🌵 Caatinga e Recôncavo Baiano',text:'Semiárido, vegetação adaptada, cultura e diversidade regional.'}
];

function svgData(title,emoji,c1,c2){const safe=title.replace(/[&<>]/g,'');const svg=`<svg xmlns='http://www.w3.org/2000/svg' width='1200' height='675' viewBox='0 0 1200 675'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop stop-color='${c1}'/><stop offset='1' stop-color='${c2}'/></linearGradient></defs><rect width='1200' height='675' fill='url(#g)'/><circle cx='1010' cy='110' r='72' fill='rgba(255,255,255,.28)'/><path d='M0 500 Q180 390 360 500 T720 480 T1200 490 V675 H0Z' fill='rgba(255,255,255,.18)'/><text x='600' y='285' text-anchor='middle' font-size='150'>${emoji}</text><text x='600' y='420' text-anchor='middle' font-family='Trebuchet MS,Arial,sans-serif' font-size='48' font-weight='700' fill='white'>${safe}</text><text x='600' y='480' text-anchor='middle' font-family='Arial,sans-serif' font-size='26' fill='rgba(255,255,255,.9)'>Expedição com Feogia</text></svg>`;return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)}
const SCENE_FALLBACKS=[['🌿','Floresta Amazônica e Rios','#16794b','#37b9b2'],['🐊','Pantanal Alagado e Planícies','#4c8e66','#8cc6cf'],['🌲','Serra Gaúcha e Araucárias','#2f6d4e','#719bc1'],['⛰️','Cachoeiras e Chapada Diamantina','#9f6338','#43a9cf'],['🏜️','Lençóis e Delta do Piauí','#e7ba66','#4bbdd1'],['🌊','Ceará: Praias e Serra','#39a4d8','#71b864'],['🐚','Litoral Sul e Agreste','#2aa3bc','#c6a35e'],['🌵','Caatinga e Recôncavo Baiano','#c78648','#e1c06a']];
function sceneFallback(i){const f=SCENE_FALLBACKS[i%SCENE_FALLBACKS.length];return svgData(f[1],f[0],f[2],f[3])}
function installImageFallbacks(){const mascot=$('.mascot');if(mascot)mascot.addEventListener('error',()=>{mascot.src=svgData('FEOGIA','🌎','#158bb8','#6fbf5f')},{once:true});const main=$('#sceneImage');if(main)main.addEventListener('error',()=>{const idx=Math.max(0,SCENES.findIndex(x=>x.title===$('#sceneTitle').textContent));main.src=sceneFallback(idx)});const result=$('.result-visual img');if(result)result.addEventListener('error',()=>{result.src=svgData('Resumo da Rodada','🏆','#72543b','#cf9b4c')},{once:true})}

function renderSceneThumbs(){const box=$('#sceneThumbs');box.innerHTML='';SCENES.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.className='scene-thumb'+(i===0?' active':'');b.innerHTML=`<img src="${s.src}" alt=""><small>${s.title.replace(/^.. /,'')}</small>`;b.querySelector('img').addEventListener('error',e=>{e.currentTarget.src=sceneFallback(i)},{once:true});b.addEventListener('click',()=>setScene(i,true));box.appendChild(b)})}
function setScene(i,manual=false){const s=SCENES[i%SCENES.length];const img=$('#sceneImage');img.style.opacity='.35';setTimeout(()=>{img.src=s.src;img.alt=s.title;$('#sceneTitle').textContent=s.title;$('#sceneText').textContent=s.text;img.style.opacity='1'},130);document.querySelectorAll('.scene-thumb').forEach((b,n)=>b.classList.toggle('active',n===i%SCENES.length));if(manual)say(`${s.title}. ${s.text}`,false)}
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
const BNCC_FALLBACK={
6:{'Continentes':'EF06GE05','Localização':'EF06GE08','Orientação':'EF06GE08','Coordenadas':'EF06GE08','Linhas imaginárias':'EF06GE03','Relevo':'EF06GE05','Oceanos':'EF06GE04','Climas':'EF06GE03','Vegetação':'EF06GE05','População':'EF06GE11','Cartografia':'EF06GE08','Escala':'EF06GE08','Atmosfera':'EF06GE03','Clima':'EF06GE05','Clima e vegetação':'EF06GE05','Paisagem':'EF06GE01'},
7:{'Continentes':'EF07GE09','África':'EF07GE09','Ásia':'EF07GE04','Europa':'EF07GE09','Oceania':'EF07GE09','Antártida':'EF07GE09','Oceanos':'EF07GE09','Climas':'EF07GE11','Vegetação':'EF07GE11','População':'EF07GE04','Biomas':'EF07GE11','Gráficos':'EF07GE10','Mapa temático':'EF07GE09','Transportes':'EF07GE07','Industrialização':'EF07GE08'}
};
function skillFor(q){return q.b||BNCC_FALLBACK[grade][q.t]||(grade===6?'EF06GE11':'EF07GE11')}
function cognitiveName(){return level===1?'Reconhecimento e compreensão':level===2?'Aplicação e interpretação':'Análise e raciocínio geográfico'}
function cleanSpeech(s){return s.replace(/[🌍🌎🌏🧭🗺️🏆⭐💡✅]/g,'')}
function stopVoice(){if('speechSynthesis'in window) speechSynthesis.cancel();mascotStage.classList.remove('talking');speechBox.classList.remove('speaking')}
function speak(text){stopVoice();if(!voiceOn||!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(cleanSpeech(text));u.lang='pt-BR';u.rate=.96;u.pitch=1.08;u.onstart=()=>{mascotStage.classList.add('talking');speechBox.classList.add('speaking')};u.onend=u.onerror=()=>{mascotStage.classList.remove('talking');speechBox.classList.remove('speaking')};speechSynthesis.speak(u)}
function say(text,doVoice=true){speechText.textContent=text;if(doVoice)speak(text)}
function tone(type){if(!fxOn)return;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;if(!audioCtx)audioCtx=new AC();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime;o.connect(g);g.connect(audioCtx.destination);o.type=type==='good'?'sine':'triangle';o.frequency.setValueAtTime(type==='good'?650:240,t);o.frequency.exponentialRampToValueAtTime(type==='good'?920:150,t+.2);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.09,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+.28);o.start(t);o.stop(t+.3)}catch(e){}}
function react(type){mascotStage.classList.remove('celebrate','wrong');void mascotStage.offsetWidth;mascotStage.classList.add(type);setTimeout(()=>mascotStage.classList.remove(type),1400)}
function confetti(){const colors=['#4ebd55','#ffd44d','#ff914d','#39aee1','#ef5b5b'];for(let i=0;i<28;i++){const c=document.createElement('i');c.className='confetti';c.style.left=(5+Math.random()*90)+'%';c.style.top=(Math.random()*18)+'px';c.style.background=colors[i%colors.length];c.style.animationDelay=(Math.random()*.2)+'s';mascotStage.appendChild(c);setTimeout(()=>c.remove(),1500)}}
function show(screen){['seriesScreen','levelScreen','gameScreen','resultScreen'].forEach(id=>$('#'+id).classList.toggle('hidden',id!==screen))}
function selectGrade(g){grade=g;$('#levelSubtitle').textContent=`Você escolheu o ${g}º ano. Agora selecione a dificuldade da missão.`;show('levelScreen');say(`Ótima escolha! ${g}º ano selecionado. Agora escolha o nível da nossa aventura!`)}
function selectLevel(l){level=l;startGame()}
function bank(){return currentQuestions}
function levelName(){return level===1?'Explorador':level===2?'Cartógrafo':'Mestre'}
function renderRoute(){const r=$('#route');r.innerHTML='';PHASES.forEach((p,i)=>{const s=document.createElement('span');s.className='phase'+(i===index?' active':'')+(i<index?' done':'');s.textContent=`${p[0]} ${p[1]}`;r.appendChild(s)});const a=r.querySelector('.active');if(a)a.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'})}
function updateStats(){const done=Math.min(index,10);$('#score').textContent=`⭐ ${hits}/10`;$('#hits').textContent=hits;$('#phaseNum').textContent=Math.min(index+1,10);$('#progressText').textContent=`${done}/10`;$('#progress').style.width=`${done*10}%`}
function renderQuestion(){answered=false;const q=bank()[index];const skill=skillFor(q);$('#badges').innerHTML=`<span class="badge">${grade}º ANO</span><span class="badge level${level}">Nível ${level} • ${levelName()}</span><span class="badge">${q.t}</span><span class="badge bncc-badge">${skill}</span>`;$('#bnccSkill').textContent=`Habilidade em foco: ${skill}`;$('#cognitiveLevel').textContent=`• ${cognitiveName()}`;$('#phaseTitle').textContent=`${PHASES[index][0]} Fase ${index+1} de 10 • ${PHASES[index][1]}`;$('#question').textContent=q.q;const a=$('#answers');a.innerHTML='';q.o.forEach((text,n)=>{const b=document.createElement('button');b.type='button';b.className='answer';b.textContent=`${String.fromCharCode(65+n)}) ${text}`;b.addEventListener('click',()=>choose(n,b));a.appendChild(b)});$('#hintBox').classList.add('hidden');$('#feedbackBox').classList.add('hidden');$('#hintBtn').disabled=false;$('#nextBtn').disabled=true;$('#nextBtn').textContent=index===9?'Ver resultado 🏆':'Próxima fase →';setScene(index%SCENES.length);renderRoute();updateStats();say(`${introLines[index]} ${q.q}`)}
function choose(n,button){if(answered)return;answered=true;const q=bank()[index],buttons=[...document.querySelectorAll('.answer')],correct=n===q.a;buttons.forEach(b=>b.disabled=true);buttons[q.a].classList.add('correct');if(correct){hits++;button.classList.add('correct');buttons.forEach((b,i)=>{if(i!==n)b.classList.add('dim')});$('#feedbackBox').textContent=`✅ Muito bem! ${q.e}`;tone('good');react('celebrate');confetti();say(`Muito bem! ${q.e}`)}else{button.classList.add('wrong');buttons.forEach((b,i)=>{if(i!==n&&i!==q.a)b.classList.add('dim')});$('#feedbackBox').textContent=`🧭 Quase! A resposta correta é ${String.fromCharCode(65+q.a)}. ${q.e}`;tone('bad');react('wrong');say(`Quase! A resposta correta é ${q.o[q.a]}. ${q.e}`)}answersLog.push({topic:q.t,correct,bncc:skillFor(q)});$('#feedbackBox').classList.remove('hidden');$('#hintBtn').disabled=true;$('#nextBtn').disabled=false;updateStats()}
function showHint(){if(answered)return;const q=bank()[index];$('#hintBox').textContent=`💡 Dica: ${q.h}`;$('#hintBox').classList.remove('hidden');$('#hintBtn').disabled=true;say(`Dica: ${q.h}`)}
function classification(){if(hits<=3)return['Explorador Iniciante','Você começou a construir sua rota geográfica. Reveja as explicações e tente novamente!'];if(hits<=6)return['Explorador em Treinamento','Boa viagem! Você já reconhece muitos conceitos e está pronto para avançar.'];if(hits<=8)return['Grande Explorador','Excelente desempenho! Seu raciocínio geográfico está bem orientado.'];return['Mestre da Geografia','Fantástico! Você dominou a missão com precisão de cartógrafo.']}
function finish(){stopVoice();show('resultScreen');const [rank,msg]=classification();$('#finalScore').textContent=`${grade}º ano • Nível ${level} (${levelName()}) • ${hits} acertos em 10 questões.`;$('#rank').textContent=rank;$('#finalTalk').textContent=`Feogia diz: “${msg}”`;const bd=$('#breakdown');bd.innerHTML='';answersLog.forEach((x,i)=>{const d=document.createElement('div');d.className='result-row';d.textContent=`${x.correct?'✅':'🧭'} Fase ${i+1} • ${x.topic} • ${x.bncc}`;bd.appendChild(d)});react('celebrate');confetti();say(msg);window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}
function startGame(){index=0;hits=0;answered=false;answersLog=[];const key=`${grade}-${level}`;currentQuestions=shuffle([...(BANKS[key]||[]),...(EXTRA_BANKS[key]||[])]).slice(0,10);show('gameScreen');renderQuestion();window.scrollTo({top:$('#gameScreen').offsetTop-8,behavior:'smooth'})}
function leaveGame(){stopVoice();show('levelScreen');say(`Missão pausada. Você continua no ${grade}º ano e pode escolher outro nível.`)}
document.querySelectorAll('[data-grade]').forEach(b=>b.addEventListener('click',()=>selectGrade(Number(b.dataset.grade))));document.querySelectorAll('[data-level]').forEach(b=>b.addEventListener('click',()=>selectLevel(Number(b.dataset.level))));$('#backSeries').addEventListener('click',()=>{grade=null;show('seriesScreen');say('Escolha novamente sua série, explorador!')});$('#hintBtn').addEventListener('click',showHint);$('#nextBtn').addEventListener('click',()=>{if(!answered)return;index++;index>=10?finish():renderQuestion()});$('#leaveGame').addEventListener('click',leaveGame);$('#replay').addEventListener('click',startGame);$('#changeLevel').addEventListener('click',()=>{show('levelScreen');say(`Escolha um novo nível para o ${grade}º ano!`)});$('#voiceBtn').addEventListener('click',()=>{voiceOn=!voiceOn;if(!voiceOn)stopVoice();$('#voiceBtn').textContent=voiceOn?'🔊 Voz ligada':'🔇 Voz desligada';if(voiceOn)say('Minha voz voltou! Vamos explorar o planeta!')});$('#fxBtn').addEventListener('click',()=>{fxOn=!fxOn;$('#fxBtn').textContent=fxOn?'🎵 Efeitos ligados':'🔕 Efeitos desligados';if(fxOn)tone('good')});if(!('speechSynthesis'in window)){$('#voiceBtn').textContent='🔇 Voz não disponível neste navegador';$('#voiceBtn').disabled=true;voiceOn=false}installImageFallbacks();renderSceneThumbs();setScene(0);
