<?php
require __DIR__.'/layout.php'; require_login();
$id=(int)($_GET['report']??0);$s=$pdo->prepare('SELECT r.*,c.name client_name,c.document client_document,c.contract_no,c.object_text FROM account_reports r JOIN clients c ON c.id=r.client_id WHERE r.id=?');$s->execute([$id]);$r=$s->fetch();if(!$r){http_response_code(404);exit('Prestação não encontrada.');}
$s=$pdo->prepare('SELECT * FROM invoices WHERE report_id=? ORDER BY issue_date,id');$s->execute([$id]);$nfs=$s->fetchAll();$s=$pdo->prepare('SELECT * FROM transactions WHERE report_id=? ORDER BY transaction_date,id');$s->execute([$id]);$tx=$s->fetchAll();
$gross=$ret=$in=$out=0;$byCat=[];$byParty=[];foreach($nfs as $n){$gross+=(float)$n['gross_amount'];$ret+=(float)$n['gross_amount']-(float)$n['net_amount'];}foreach($tx as $t){if($t['type']==='entrada')$in+=(float)$t['amount'];else{$out+=(float)$t['amount'];$cat=$t['category']?:'Sem categoria';$byCat[$cat]=($byCat[$cat]??0)+(float)$t['amount'];$p=$t['party']?:'Não informado';$byParty[$p]=($byParty[$p]??0)+(float)$t['amount'];}}arsort($byCat);arsort($byParty);$balance=(float)$r['opening_balance']+$in-$out;
page_top('Relatório de Prestação de Contas');
?>
<div class="no-print actions"><button onclick="window.print()" class="gold">Imprimir / Salvar em PDF</button><a class="btn light" href="prestacao.php?report=<?=$id?>">Voltar</a></div>
<section class="card" style="margin-top:15px"><h1 style="margin:0">RELATÓRIO DE PRESTAÇÃO DE CONTAS</h1><p><b>Cliente/Órgão:</b> <?=h($r['client_name'])?><br><b>CNPJ/CPF:</b> <?=h($r['client_document']?:'—')?> &nbsp; <b>Contrato:</b> <?=h($r['contract_no']?:'—')?><br><b>Período:</b> <?=h($r['reference_period']?:'—')?> &nbsp; <b>Prestação nº:</b> <?=$r['id']?></p><p><b>Objeto:</b> <?=nl2br(h($r['object_text']?:'—'))?></p></section>
<div class="grid g4" style="margin-top:15px"><div class="card"><div class="muted">Faturado bruto</div><div class="metric"><?=money($gross)?></div></div><div class="card"><div class="muted">Retenções</div><div class="metric red"><?=money($ret)?></div></div><div class="card"><div class="muted">Entradas efetivas</div><div class="metric green"><?=money($in)?></div></div><div class="card"><div class="muted">Saídas</div><div class="metric red"><?=money($out)?></div></div></div>
<div class="card" style="margin-top:15px"><div class="muted">SALDO FINAL</div><div class="metric <?=$balance<0?'red':'green'?>"><?=money($balance)?></div><div class="muted">Saldo inicial <?=money($r['opening_balance'])?> + entradas <?=money($in)?> - saídas <?=money($out)?></div></div>
<div class="section-title"><h2>1. Notas fiscais e descontos/retenções</h2></div><div class="tablewrap"><table><thead><tr><th>Data</th><th>NF</th><th>Bruto</th><th>ISS</th><th>INSS</th><th>IR</th><th>PIS</th><th>COFINS</th><th>CSLL</th><th>Outros</th><th>Líquido</th></tr></thead><tbody><?php foreach($nfs as $n):?><tr><td><?=h($n['issue_date'])?></td><td><?=h($n['number'])?></td><td><?=money($n['gross_amount'])?></td><td><?=money($n['iss'])?></td><td><?=money($n['inss'])?></td><td><?=money($n['irrf'])?></td><td><?=money($n['pis'])?></td><td><?=money($n['cofins'])?></td><td><?=money($n['csll'])?></td><td><?=money($n['other_discount'])?></td><td><b><?=money($n['net_amount'])?></b></td></tr><?php endforeach;?></tbody></table></div>
<div class="section-title"><h2>2. Entradas e saídas</h2></div><div class="tablewrap"><table><thead><tr><th>Data</th><th>Tipo</th><th>Descrição</th><th>Origem/Destino</th><th>Documento</th><th>Pagamento</th><th>Categoria</th><th>Valor</th></tr></thead><tbody><?php foreach($tx as $t):?><tr><td><?=h($t['transaction_date'])?></td><td><?=h(strtoupper($t['type']))?></td><td><?=h($t['description'])?></td><td><?=h($t['party']?:'—')?></td><td><?=h($t['document_no']?:'—')?></td><td><?=h($t['payment_method']?:'—')?></td><td><?=h($t['category']?:'—')?></td><td><?=money($t['amount'])?></td></tr><?php endforeach;?></tbody></table></div>
<div class="grid g2" style="margin-top:15px"><section class="card"><h2>3. Para onde o dinheiro foi — por categoria</h2><?php foreach($byCat as $k=>$v):?><div style="display:flex;justify-content:space-between;border-bottom:1px solid #e4e8ef;padding:8px 0"><span><?=h($k)?></span><b><?=money($v)?></b></div><?php endforeach;?></section><section class="card"><h2>4. Para quem o dinheiro foi — por favorecido</h2><?php foreach($byParty as $k=>$v):?><div style="display:flex;justify-content:space-between;border-bottom:1px solid #e4e8ef;padding:8px 0"><span><?=h($k)?></span><b><?=money($v)?></b></div><?php endforeach;?></section></div>
<section class="card" style="margin-top:15px"><p>Declaro que os lançamentos acima representam a movimentação registrada nesta caderneta de prestação de contas, acompanhada dos documentos e comprovantes anexados no sistema.</p><div style="height:65px"></div><div style="border-top:1px solid #172033;width:280px;text-align:center;padding-top:5px">Responsável pela prestação de contas</div></section>
<?php audit('emitiu relatório','Prestação #'.$id); page_bottom(); ?>
