const questions=[
{topic:'Princípios',q:'Qual princípio exige ampla divulgação dos atos da contratação pública, ressalvadas as hipóteses legais de sigilo?',a:['Publicidade','Pessoalidade','Exclusividade','Informalidade'],c:0,e:'A publicidade está expressamente entre os princípios da Lei nº 14.133/2021 e favorece o controle e a transparência.'},
{topic:'Princípios',q:'Qual princípio reforça que a contratação deve ser preparada antes da execução, com definição da necessidade e da solução?',a:['Planejamento','Sigilo','Improvisação','Subordinação privada'],c:0,e:'O planejamento é princípio expresso da Lei nº 14.133/2021 e estrutura a fase preparatória da contratação.'},
{topic:'Governança',q:'O princípio da segregação de funções busca principalmente:',a:['Evitar concentração indevida de atividades críticas na mesma pessoa','Eliminar a fiscalização do contrato','Permitir decisões sem registro','Dispensar controles internos'],c:0,e:'A segregação de funções reduz riscos ao distribuir atividades incompatíveis entre agentes diferentes.'},
{topic:'Licitação',q:'Para aquisição de bens e serviços comuns, qual modalidade é definida pela Lei nº 14.133/2021 como adequada quando adotado o critério de menor preço ou maior desconto?',a:['Pregão','Concurso','Leilão','Diálogo competitivo'],c:0,e:'O pregão é a modalidade destinada à aquisição de bens e serviços comuns, observadas as regras legais.'},
{topic:'Licitação',q:'Qual modalidade envolve diálogos com licitantes previamente selecionados para desenvolver alternativas capazes de atender uma necessidade complexa?',a:['Diálogo competitivo','Leilão','Concurso','Convite'],c:0,e:'O diálogo competitivo foi previsto para situações em que a Administração precisa discutir soluções antes da proposta final.'},
{topic:'Contratação direta',q:'A inexigibilidade de licitação ocorre, em regra, quando:',a:['A competição é inviável','Há sempre pelo menos dez fornecedores','O contrato tem baixo valor em qualquer hipótese','A Administração prefere não licitar'],c:0,e:'A característica central da inexigibilidade é a inviabilidade de competição, conforme as hipóteses legais.'},
{topic:'Contratação direta',q:'Na dispensa de licitação, a contratação direta:',a:['Depende de hipótese autorizada em lei','Pode ser feita sem processo administrativo','Dispensa justificativa de preço','Elimina a necessidade de motivação'],c:0,e:'A dispensa somente pode ocorrer nas hipóteses legais e continua exigindo instrução, motivação e justificativas próprias.'},
{topic:'Planejamento',q:'O Estudo Técnico Preliminar (ETP) serve principalmente para:',a:['Evidenciar o problema e avaliar a melhor solução para a necessidade pública','Substituir automaticamente o contrato','Aplicar sanção ao fornecedor','Autorizar pagamento sem liquidação'],c:0,e:'O ETP integra o planejamento e ajuda a demonstrar a necessidade, alternativas e solução mais adequada.'},
{topic:'Planejamento',q:'O Termo de Referência é utilizado para:',a:['Definir requisitos, condições e características da contratação de bens ou serviços','Registrar apenas pagamentos realizados','Substituir a fiscalização do contrato','Criar modalidade de licitação'],c:0,e:'O Termo de Referência detalha o objeto e as condições necessárias para orientar a contratação.'},
{topic:'Fiscalização',q:'Quem acompanha e fiscaliza a execução contratual em nome da Administração?',a:['Um ou mais fiscais do contrato especialmente designados','Somente o fornecedor','Qualquer cidadão sem designação','Apenas a instituição financeira'],c:0,e:'O art. 117 prevê o acompanhamento e a fiscalização por um ou mais fiscais especialmente designados pela Administração.'},
{topic:'Fiscalização',q:'Ao identificar falhas na execução, o fiscal do contrato deve:',a:['Registrar as ocorrências e determinar o necessário para regularização dentro de sua competência','Apagar os registros para evitar conflito','Alterar sozinho qualquer cláusula contratual','Efetuar pagamento antecipado'],c:0,e:'O fiscal deve manter registro próprio das ocorrências e agir para a regularização das faltas ou defeitos observados.'},
{topic:'Execução',q:'Durante toda a execução do contrato, o contratado deve:',a:['Manter as condições exigidas para a habilitação e qualificação, conforme o contrato e a lei','Deixar de cumprir obrigações fiscais após a assinatura','Alterar o objeto sem autorização','Recusar toda fiscalização'],c:0,e:'A manutenção das condições de habilitação e qualificação é obrigação contratual prevista na Lei nº 14.133/2021.'},
{topic:'Alterações',q:'Nas alterações unilaterais quantitativas de obras, serviços ou compras, qual é o limite geral de acréscimos ou supressões sobre o valor inicial atualizado?',a:['25%','5%','75%','100%'],c:0,e:'O art. 125 estabelece, como regra geral, o limite de 25% para acréscimos ou supressões nessas alterações.'},
{topic:'Alterações',q:'No caso de reforma de edifício ou equipamento, qual é o limite legal para acréscimos unilaterais?',a:['50%','10%','25%','80%'],c:0,e:'Para acréscimos em reforma de edifício ou equipamento, o art. 125 prevê limite de 50%.'},
{topic:'Alterações',q:'Uma alteração unilateral do contrato pode transformar completamente o objeto originalmente contratado?',a:['Não, a alteração não pode transfigurar o objeto','Sim, sem qualquer limite','Sim, desde que não haja registro','Somente se o fornecedor decidir sozinho'],c:0,e:'A Lei veda que alterações unilaterais transfigurem o objeto da contratação.'},
{topic:'Equilíbrio econômico',q:'O equilíbrio econômico-financeiro do contrato representa:',a:['A preservação da relação entre encargos assumidos e remuneração pactuada','A garantia de lucro ilimitado ao contratado','A proibição de qualquer revisão contratual','A eliminação de riscos previstos na contratação'],c:0,e:'O equilíbrio econômico-financeiro protege a relação originalmente estabelecida entre encargos e remuneração, nos termos legais.'},
{topic:'Sanções',q:'Qual conjunto contém apenas sanções administrativas previstas na Lei nº 14.133/2021?',a:['Advertência, multa, impedimento de licitar e contratar e declaração de inidoneidade','Prisão, cassação de passaporte e multa de trânsito','Apenas advertência verbal e suspensão salarial','Desapropriação e prisão civil'],c:0,e:'Essas quatro espécies de sanção administrativa estão previstas na Lei nº 14.133/2021.'},
{topic:'Transparência',q:'A divulgação do contrato e de seus aditamentos no PNCP é, em regra:',a:['Condição indispensável para sua eficácia','Apenas uma recomendação sem efeito jurídico','Obrigatória somente para contratos privados','Dispensada em todas as contratações diretas'],c:0,e:'O art. 94 estabelece a divulgação no PNCP como condição indispensável para a eficácia do contrato e de seus aditamentos.'},
{topic:'PNCP',q:'No caso de contrato resultante de licitação, qual prazo o art. 94 prevê para divulgação no PNCP, contado da assinatura?',a:['20 dias úteis','2 dias corridos','60 dias úteis','1 ano'],c:0,e:'Para contratos decorrentes de licitação, o art. 94 prevê divulgação em até 20 dias úteis da assinatura.'},
{topic:'PNCP',q:'No caso de contratação direta, qual prazo o art. 94 prevê para divulgação no PNCP, contado da assinatura?',a:['10 dias úteis','30 dias corridos','90 dias úteis','24 horas em qualquer caso'],c:0,e:'Para contratação direta, o art. 94 prevê divulgação em até 10 dias úteis da assinatura.'},
{topic:'Urgência',q:'Segundo o art. 94, §1º, contratos celebrados em caso de urgência:',a:['Têm eficácia a partir da assinatura e devem ser publicados nos prazos legais','Nunca precisam ser publicados','Só têm eficácia depois de um ano','Dispensam processo administrativo'],c:0,e:'A lei admite eficácia desde a assinatura nos casos de urgência, mantendo a obrigação de publicação nos prazos previstos.'},
{topic:'Modalidades',q:'Qual alternativa apresenta somente modalidades da Lei nº 14.133/2021?',a:['Pregão, concorrência, concurso, leilão e diálogo competitivo','Convite, tomada de preços e consulta','Credenciamento, dispensa e inexigibilidade','Cotação, concurso e convite'],c:0,e:'A Lei nº 14.133/2021 prevê pregão, concorrência, concurso, leilão e diálogo competitivo como modalidades de licitação.'},
{topic:'Julgamento',q:'O princípio do julgamento objetivo exige que:',a:['As propostas sejam avaliadas conforme critérios previamente definidos','O vencedor seja escolhido por preferência pessoal','Os critérios sejam criados depois da abertura das propostas','A decisão não precise de motivação'],c:0,e:'O julgamento objetivo exige critérios definidos previamente e aplicados de forma impessoal.'},
{topic:'Sustentabilidade',q:'A Lei nº 14.133/2021 inclui entre seus princípios:',a:['Desenvolvimento nacional sustentável','Sigilo absoluto','Preferência pessoal','Ausência de planejamento'],c:0,e:'O desenvolvimento nacional sustentável está expressamente previsto no art. 5º.'},
{topic:'Transparência',q:'Transparência nas contratações públicas significa, entre outros aspectos:',a:['Disponibilizar informações claras e permitir controle dos atos, observadas as exceções legais','Ocultar todos os documentos até o fim do contrato','Proibir acesso aos atos públicos','Substituir a publicidade por comunicação informal'],c:0,e:'A transparência reforça o acesso claro às informações e o controle da contratação, respeitadas as hipóteses legais de sigilo.'},
{topic:'Edital',q:'Pelo princípio da vinculação ao edital:',a:['Administração e licitantes devem observar as regras do instrumento convocatório','O edital pode ser ignorado após a publicação','Somente o fornecedor está vinculado','Critérios podem ser mudados sem publicidade'],c:0,e:'A vinculação ao edital exige respeito às regras previamente estabelecidas no instrumento convocatório.'},
{topic:'Subcontratação',q:'A subcontratação de partes do objeto pelo contratado:',a:['Pode ser admitida nos limites autorizados pela Administração e pela legislação','É sempre livre e ilimitada','É sempre proibida, sem exceção','Transfere automaticamente todo o contrato'],c:0,e:'A Lei admite subcontratação de partes do objeto quando observados os limites e condições autorizados pela Administração.'},
{topic:'Recebimento',q:'Conforme a natureza do objeto, o recebimento contratual pode ocorrer:',a:['Provisória e definitivamente, segundo os critérios legais e contratuais','Somente de forma verbal','Apenas antes da entrega','Sem qualquer verificação'],c:0,e:'A Lei disciplina recebimento provisório e definitivo, de acordo com o tipo de objeto e as condições aplicáveis.'},
{topic:'Pagamento',q:'A ordem cronológica de pagamentos pela Administração tem como objetivo principal:',a:['Organizar pagamentos com impessoalidade e previsibilidade, ressalvadas hipóteses legais justificadas','Permitir escolha livre de quem recebe primeiro','Eliminar registros financeiros','Autorizar pagamento sem comprovação da execução'],c:0,e:'A ordem cronológica busca dar previsibilidade, controle e impessoalidade aos pagamentos, observadas as exceções legalmente justificadas.'},
{topic:'Interesse público',q:'Na gestão de um contrato administrativo, uma decisão da Administração deve ser orientada principalmente por:',a:['Interesse público, legalidade e motivação','Preferência pessoal do gestor','Vantagem privada do fiscal','Ausência de registro'],c:0,e:'A gestão contratual deve observar o interesse público e os princípios da legalidade, motivação, transparência e demais regras aplicáveis.'}
];
const armor=[
{name:'Lobo Recruta',icon:'🐺',text:'A jornada começa agora. Acerte questões para equipar o Lobo.'},
{name:'Explorador KMO',icon:'🐺',text:'Primeira evolução conquistada: o Lobo domina os fundamentos.'},
{name:'Guardião dos Contratos',icon:'🐺🛡️',text:'Escudo equipado. O conhecimento começa a proteger a missão.'},
{name:'Fiscal de Elite',icon:'🐺⚔️',text:'O Lobo já domina fiscalização, execução e controle.'},
{name:'Comandante KMO',icon:'🐺🛡️',text:'Armadura avançada liberada. Estratégia e governança em alta.'},
{name:'Mestre das Licitações',icon:'🐺⚔️',text:'Nível de mestre: visão ampla sobre licitações e contratos.'},
{name:'Lobo Supremo KMO',icon:'🐺👑',text:'Armadura máxima conquistada. Missão KMO concluída com excelência.'}
];
let index=0,score=0,streak=0,best=0,xp=0,answered=false,lastLevel=0;
const $=s=>document.querySelector(s);
const qn=$('#questionNumber'),topic=$('#topic'),question=$('#question'),answers=$('#answers'),feedback=$('#feedback'),next=$('#nextBtn'),scoreEl=$('#score'),streakEl=$('#streak'),bestEl=$('#best'),xpEl=$('#xp'),armorLevel=$('#armorLevel'),armorBadge=$('#armorBadge'),armorText=$('#armorText'),armorBar=$('#armorBar'),mainBar=$('#mainBar'),wolf=$('#wolf'),game=$('#game'),result=$('#result');
function level(){return Math.min(6,Math.floor(score/5))}
function updateArmor(){const l=level(),data=armor[l];armorLevel.textContent=l;armorBadge.textContent=data.name;armorText.textContent=data.text;armorBar.style.width=`${(l/6)*100}%`;wolf.textContent=data.icon;if(l>lastLevel){wolf.classList.remove('level-up');void wolf.offsetWidth;wolf.classList.add('level-up');lastLevel=l}}
function render(){answered=false;next.disabled=true;feedback.hidden=true;feedback.className='feedback';const item=questions[index];qn.textContent=index+1;topic.textContent=item.topic;question.textContent=item.q;answers.innerHTML='';item.a.forEach((label,i)=>{const b=document.createElement('button');b.className='answer';b.type='button';b.innerHTML=`<span>${String.fromCharCode(65+i)}</span><strong>${label}</strong>`;b.addEventListener('click',()=>choose(i,b));answers.appendChild(b)});mainBar.style.width=`${(index/questions.length)*100}%`;scoreEl.textContent=score;streakEl.textContent=streak;bestEl.textContent=best;xpEl.textContent=xp;updateArmor()}
function choose(choice,button){if(answered)return;answered=true;const item=questions[index];[...answers.children].forEach((b,i)=>{b.disabled=true;if(i===item.c)b.classList.add('correct')});if(choice===item.c){score++;streak++;best=Math.max(best,streak);xp+=100+(streak-1)*20;button.classList.add('correct');feedback.textContent=`Acertou! ${item.e}`;feedback.classList.add('good')}else{streak=0;button.classList.add('wrong');feedback.textContent=`Resposta correta: ${item.a[item.c]}. ${item.e}`;feedback.classList.add('bad')}feedback.hidden=false;scoreEl.textContent=score;streakEl.textContent=streak;bestEl.textContent=best;xpEl.textContent=xp;updateArmor();next.disabled=false;next.textContent=index===questions.length-1?'Ver resultado →':'Próxima pergunta →'}
function advance(){if(!answered)return;if(index<questions.length-1){index++;render()}else{finish()}}
function finish(){mainBar.style.width='100%';game.hidden=true;result.hidden=false;$('#finalScore').textContent=`${score}/${questions.length}`;let title,text;if(score===30){title='Lobo Supremo: desempenho perfeito';text='Você acertou todos os desafios e liberou a armadura máxima do Quiz do Lobo KMO.'}else if(score>=24){title='Excelente domínio dos contratos públicos';text='Seu desempenho foi de alto nível. Você avançou quase toda a trilha de armadura.'}else if(score>=18){title='Boa base de conhecimento';text='Você concluiu a missão com bom aproveitamento. Revise os pontos em que errou e tente subir mais um nível.'}else{title='Treinamento concluído';text='A missão foi concluída. Jogue novamente para reforçar os conceitos e evoluir a armadura do Lobo.'}$('#resultTitle').textContent=title;$('#resultText').textContent=text;result.scrollIntoView({behavior:'smooth',block:'center'})}
function reset(){index=0;score=0;streak=0;best=0;xp=0;lastLevel=0;game.hidden=false;result.hidden=true;next.textContent='Próxima pergunta →';render();window.scrollTo({top:0,behavior:'smooth'})}
next.addEventListener('click',advance);$('#restartBtn').addEventListener('click',reset);$('#playAgain').addEventListener('click',reset);render();
